"""first alembic version

Revision ID: 4674682f0258
Revises: 
Create Date: 2025-01-18 11:49:03.164912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4674682f0258'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usermodels',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sa.Enum('user', 'admin', 'superuser', name='rolebase'), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('hash_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_usermodels_email'), 'usermodels', ['email'], unique=True)
    op.create_index(op.f('ix_usermodels_first_name'), 'usermodels', ['first_name'], unique=False)
    op.create_index(op.f('ix_usermodels_last_name'), 'usermodels', ['last_name'], unique=False)
    op.create_index(op.f('ix_usermodels_uid'), 'usermodels', ['uid'], unique=False)
    op.create_index(op.f('ix_usermodels_username'), 'usermodels', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usermodels_username'), table_name='usermodels')
    op.drop_index(op.f('ix_usermodels_uid'), table_name='usermodels')
    op.drop_index(op.f('ix_usermodels_last_name'), table_name='usermodels')
    op.drop_index(op.f('ix_usermodels_first_name'), table_name='usermodels')
    op.drop_index(op.f('ix_usermodels_email'), table_name='usermodels')
    op.drop_table('usermodels')
    # ### end Alembic commands ###
